profile: cover.out

local-prefix: terraform-provider-boxer

threshold:
  file: 70
  package: 70
  total: 80

exclude:
  paths:
    - ^pkg/generated              # exclude generated code
    - ^internal/tests/assertions  # exclude test assertions
    - main.go                     # application entry point