name: Run tests with coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_commit:
    name: Validate Code and Publish Coverage
    runs-on: ubuntu-latest-16-cores-arm-public

    if: ${{ github.ref != 'refs/heads/main' }}
    permissions:
      id-token: write      # required for dependabot PRs
      pull-requests: write # required for dependabot PRs
      contents: read       # required for dependabot PRs
    steps:
      - uses: actions/checkout@v6.0.1

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.6.6"

      - name: Setup Go
        uses: actions/setup-go@v6.1.0
        with:
          go-version: '1.24.*'

      - uses: extractions/setup-just@v3

      - name: Setup integration tests
        run: just up

      - name: Check Format
        run: gofmt -d ./

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod vendor

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1.0

      - name: Run integration tests
        run: TF_ACC=1 go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

#      See: https://github.com/SneaksAndData/terraform-provider-boxer/issues/71
#      - name: Check test coverage
#        id: coverage
#        uses: vladopajic/go-test-coverage@v2.18.0
#        continue-on-error: true # Should fail after coverage comment is posted
#        with:
#          config: .testcoverage.yaml
#
#      - name: Post coverage report
#        uses: thollander/actions-comment-pull-request@v3
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          comment-tag: coverage-report
#          message: |
#            go-test-coverage report:
#            ```${{ fromJSON(steps.coverage.outputs.report) }}```
#
#      - name: Finally check coverage
#        if: steps.coverage.outcome == 'failure'
#        shell: bash
#        run: echo "coverage check failed" && exit 1

      - name: Get logs from application pods
        if: always()
        run: |
          kubectl describe pods --namespace default || true
          echo "============================= Logs from boxer-issuer =================================================="
          kubectl logs -l app.kubernetes.io/name=boxer-issuer || true
          echo "============================= Logs from boxer-validator-nginx =-======================================="
          kubectl logs -l app.kubernetes.io/name=boxer-validator-nginx || true

